baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Tech Minimal'
paginate = 10

[taxonomies]
tag = 'tags'
category = 'categories'

[params]
subtitle = 'Clean, minimal, and adaptive theme for tech blog'
postsPerHomePage = 3

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Categories'
pageRef = '/categories'
weight = 30

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 40

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
