baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Tech Minimal'
copyright = 'This is your copyright notice.'

[pagination]
pagerSize = 10

# https://discourse.gohugo.io/t/how-can-i-force-tags-to-be-all-lowercase/48420/2
titleCaseStyle = 'none'

[taxonomies]
tag = 'tags'
category = 'categories'

[params]
subtitle = 'Clean, minimal, and adaptive theme for tech blog'
postsPerHomePage = 3

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Categories'
pageRef = '/categories'
weight = 30

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 40

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
