baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Tech Minimal'
copyright = 'This is your copyright notice.'

[[params.social]]
name = "Telegram"
icon = "telegram"
url = "https://t.me/principalengineering"

[[params.social]]
name = "Youtube"
icon = "youtube"
url = "https://www.youtube.com/@principal-engineering"

[[params.social]]
name = "Gitlab"
icon = "gitlab"
url = "https://gitlab.com/principal-engineering"

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/petr-korobeinikov/hugo-theme-tech-minimal"

[[params.social]]
name = "Linkedin"
icon = "linkedin"
url = "https://www.linkedin.com/in/petr-korobeinikov/"

#[[params.social]]
#name = "RSS"
#icon = "rss"
#url = "/index.xml"

[services]
    [services.googleAnalytics]
        ID = 'G-MS0SN1LCNB'
